#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests  `find tests/qa_tests/ -name 'test_*.py'` --with-coverage --cover-package=qa_tests --with-xunit --xunit-file='nosetests_qa.xml'
