#!/bin/bash
# First, purge all .pyc files to clean the source tree,
# in case some modules were deleted or removed.

find . -name "*.pyc" -delete

nosetests tests/qa_tests/ --with-coverage --cover-package=mtoolkit --with-xunit --xunit-file='nosetests_qa.xml'
